#define INPUT_IMAGE_PATH "Samples/Images/"
#define INPUT_IMAGE_FILE "room.png"
#define INPUT_IMAGE INPUT_IMAGE_PATH INPUT_IMAGE_FILE

#define INPUT_VIDEO_PATH "Samples/Videos/"
#define INPUT_VIDEO_FILE "test.mp4"
#define INPUT_VIDEO INPUT_VIDEO_PATH INPUT_VIDEO_FILE

#define OUTPUT_VIDEO_FILE "register.avi"
#define OUTPUT_VIDEO INPUT_VIDEO_PATH OUTPUT_VIDEO_FILE

#define NUMBER_OF_REGIONS 100
#define PIXEL_COLOR_SIMILARITY_THRESHOLD 40
#define REGION_COLOR_SIMILARITY_THRESHOLD 20
#define DRAW_ONLY_BORDERS false

#define MAX_FRAME_COMPUTED_AT_ONCE 10
